# Generated by Django 5.2.12 on 2026-04-09 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('duration_hours', models.IntegerField(default=24, verbose_name='Длительность (часы)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Код доступа',
                'verbose_name_plural': 'Коды доступа',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Изображение')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML контент')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('position', models.CharField(choices=[('left', 'Левая колонка'), ('right', 'Правая колонка')], default='left', max_length=10, verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рекламный блок',
                'verbose_name_plural': 'Рекламные блоки',
            },
        ),
        migrations.CreateModel(
            name='DonationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default='4100119509404270', max_length=50, verbose_name='Номер счёта')),
                ('donation_title', models.CharField(default='Поддержать проект', max_length=100, verbose_name='Заголовок')),
                ('donation_description', models.TextField(default='ЮMoney (Через Сбер)', verbose_name='Описание')),
                ('yoomoney_link', models.URLField(default='https://yoomoney.ru/to/4100119509404270', verbose_name='Ссылка')),
                ('yoomoney_iframe', models.TextField(blank=True, default='<iframe src="https://yoomoney.ru/quickpay/fundraise/button?billNumber=1H13BTCQR8C.260408&" width="330" height="50" frameborder="0" allowtransparency="true" scrolling="no"></iframe>', verbose_name='iFrame кнопка')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки доната',
                'verbose_name_plural': 'Настройки доната',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('photo', models.ImageField(upload_to='people/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='CodeActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.accesscode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активация',
                'verbose_name_plural': 'Активации кодов',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Превью')),
                ('access_level', models.CharField(choices=[('L1', 'Обычный (L1)'), ('L2', 'VIP (L2)')], default='L1', max_length=2, verbose_name='Уровень доступа')),
                ('requires_code', models.BooleanField(default=False, verbose_name='Требуется код')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.person')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
