# Generated by Django 5.2.12 on 2026-04-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_polltag_pollvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='category',
        ),
    ]
