# Generated by Django 5.2.12 on 2026-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_person_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RemoveField(
            model_name='accesscode',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='accesscode',
            name='duration_days',
            field=models.IntegerField(default=1, verbose_name='Длительность (дни)'),
        ),
    ]
