# Generated by Django 5.2.12 on 2026-04-13 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_video_options_remove_accesscode_duration_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='duration_days',
            field=models.IntegerField(default=5, verbose_name='Длительность (дни)'),
        ),
        migrations.AlterField(
            model_name='donationsettings',
            name='donation_description',
            field=models.TextField(default='350р - доступ на 5 дней', verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('page', models.CharField(blank=True, max_length=255, verbose_name='Страница')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Время посещения')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': '📊 Посещения сайта',
                'ordering': ['-visited_at'],
            },
        ),
    ]
