# Generated by Django 5.2.12 on 2026-04-13 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_accesscode_duration_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_blur_intensity', models.IntegerField(default=8, help_text='Значение от 0 до 20. Чем больше - тем сильнее размытие.', verbose_name='Сила размытия закрытых видео (px)')),
                ('vip_blur_hover', models.IntegerField(default=4, help_text='Значение от 0 до 20. Меньше чем основное размытие.', verbose_name='Размытие при наведении (px)')),
                ('vip_brightness', models.FloatField(default=0.4, help_text='От 0.0 (тёмное) до 1.0 (нормальная яркость)', verbose_name='Яркость закрытых видео')),
                ('vip_brightness_hover', models.FloatField(default=0.7, help_text='От 0.0 до 1.0', verbose_name='Яркость при наведении')),
                ('donation_card', models.CharField(default='4100119509404270', max_length=50, verbose_name='Номер счёта ЮMoney')),
                ('donation_card_alt', models.CharField(default='5599 0021 3482 6538', max_length=50, verbose_name='Номер карты (альтернатива)')),
                ('donation_amount', models.IntegerField(default=350, verbose_name='Сумма доната (руб)')),
                ('donation_days', models.IntegerField(default=5, verbose_name='Дней доступа за донат')),
                ('donation_email', models.EmailField(default='caravagio2323@gmail.com', max_length=254, verbose_name='Email для чеков')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': '⚙️ Настройки сайта',
                'verbose_name_plural': '⚙️ Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='VideoViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
            ],
            options={
                'verbose_name': 'Просмотр видео',
                'verbose_name_plural': '📊 Логи просмотров видео',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.DeleteModel(
            name='DonationSettings',
        ),
        migrations.AlterModelOptions(
            name='polltag',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тег опроса', 'verbose_name_plural': '🎯 Теги опроса'},
        ),
        migrations.RemoveConstraint(
            model_name='pollvote',
            name='unique_vote_per_ip',
        ),
        migrations.RemoveConstraint(
            model_name='pollvote',
            name='unique_vote_per_user',
        ),
        migrations.AddField(
            model_name='polltag',
            name='active_question',
            field=models.CharField(blank=True, default='Предложите теги для оживления', max_length=255, verbose_name='Активный вопрос'),
        ),
        migrations.AddField(
            model_name='polltag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='question_snapshot',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос на момент голоса'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['visited_at'], name='content_sit_visited_560932_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['page', 'visited_at'], name='content_sit_page_c60bed_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('tag', 'ip_address', 'question_snapshot'), name='unique_vote_per_ip_question'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('tag', 'user', 'question_snapshot'), name='unique_vote_per_user_question'),
        ),
        migrations.AddField(
            model_name='videoviewlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoviewlog',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='content.video'),
        ),
        migrations.AddIndex(
            model_name='videoviewlog',
            index=models.Index(fields=['viewed_at'], name='content_vid_viewed__74213a_idx'),
        ),
        migrations.AddIndex(
            model_name='videoviewlog',
            index=models.Index(fields=['video', 'viewed_at'], name='content_vid_video_i_740636_idx'),
        ),
    ]
