# Generated by Django 5.2.12 on 2026-04-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_sitesettings_videoviewlog_delete_donationsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='vip_blur_hover',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='vip_blur_intensity',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='vip_brightness',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='vip_brightness_hover',
        ),
    ]
