# Generated by Django 5.2.12 on 2026-04-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_sitesettings_vip_blur_hover_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-views', '-created_at'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
