# Generated by Django 6.0.3 on 2026-04-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Изображение')),
                ('html_content', models.TextField(blank=True, help_text='Можно вставить HTML код рекламы', verbose_name='HTML контент')),
                ('link_url', models.URLField(blank=True, help_text='Куда ведет клик по рекламе', verbose_name='Ссылка')),
                ('position', models.CharField(choices=[('left', 'Левая колонка'), ('right', 'Правая колонка')], default='left', max_length=10, verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рекламный блок',
                'verbose_name_plural': 'Рекламные блоки',
            },
        ),
    ]
